const translations = {
  ru: {
    nav_services:'Услуги', nav_experience:'Опыт', nav_contacts:'Контакты', eyebrow:'Проектная разработка • Контракт • Самозанятый', hero_title:'Владимир С.', hero_subtitle:'Разработка веб-систем, интернет-магазинов и CRM', hero_copy:'Более 15 лет коммерческого опыта. Выполняю проекты полного цикла: проектирование, backend-разработка, интеграции, настройка инфраструктуры и запуск системы.', btn_telegram:'Написать в Telegram', btn_email:'Написать на Email', btn_pdf_ru:'Открыть PDF', btn_pdf_en:'Open PDF', status:'Открыт к проектному сотрудничеству', services_eyebrow:'Что могу сделать', services_title:'Закрываю разработку и поддержку сложных веб-систем', srv_crm_title:'CRM и внутренние системы', srv_crm_text:'Проектирование и разработка бизнес-систем на Laravel, интеграции, роли, автоматизация процессов.', srv_shop_title:'Интернет-магазины', srv_shop_text:'Magento, Laravel, платежные системы, подписки, каталоги, личные кабинеты и оптимизация.', srv_audit_title:'Аудит и оптимизация', srv_audit_text:'Поиск узких мест, оптимизация SQL, производительности, архитектуры и рисков безопасности.', srv_integr_title:'Интеграции и данные', srv_integr_text:'REST API, Kafka, Redis, ClickHouse, парсинг, очереди, уведомления и внешние сервисы.', profile_eyebrow:'Профиль', profile_title:'Опыт разработчика, технического руководителя и архитектора решений', profile_1:'6 лет управлял собственной веб-студией: оценка, планирование, команда, релизы, коммуникация с заказчиками.', profile_2:'Специализируюсь на архитектуре, highload, интеграциях, аудите производительности и поддержке legacy-проектов.', profile_3:'Могу взять проект полного цикла: от идеи и требований до запуска и дальнейшего развития.', tech_eyebrow:'Стек', tech_title:'Технологии', exp_eyebrow:'Опыт', exp_title:'Ключевые проекты',
    exp_headmage_role:'Основатель / технический директор веб-студии', exp_headmage_1:'Руководил собственной веб-студией, специализировавшейся на Laravel, Magento, CRM и e-commerce проектах.', exp_headmage_2:'Проектировал архитектуру интернет-магазинов, CRM-систем и интеграционных решений для российских и зарубежных заказчиков.', exp_headmage_3:'Отвечал за полный цикл реализации: оценка, планирование, разработка, релизы, запуск и дальнейшая поддержка.', exp_headmage_4:'Организовывал процессы разработки, Code Review, CI/CD и выпуск релизов с использованием Jenkins.',
    exp_saby_role:'Руководитель подразделения / ведущий Python-разработчик', exp_saby_1:'Развивал платформу поиска, обработки и анализа данных о компаниях и владельцах.', exp_saby_2:'Разрабатывал функционал поиска, фильтрации и обработки больших объемов данных на Python и PostgreSQL.', exp_saby_3:'Внедрил практику автоматических тестов и TDD для повышения качества разработки.', exp_saby_4:'Оптимизировал бизнес-логику и SQL-запросы, повышая производительность платформы.', exp_saby_5:'Подготавливал и декомпозировал задачи, проводил Code Review и участвовал в развитии процессов разработки.',
    exp_topgo_role:'Ведущий PHP-разработчик / архитектор микросервисов', exp_topgo_1:'Спроектировал и реализовал отказоустойчивый микросервис уведомлений для агрегатора курьерской доставки.', exp_topgo_2:'Внедрил Kafka для быстрой и бесперебойной доставки уведомлений курьерам.', exp_topgo_3:'Интегрировал ClickHouse для хранения аналитических данных, логов и истории действий.', exp_topgo_4:'Настроил CI/CD процессы автоматической сборки и деплоя в инфраструктуре Yandex Cloud.', exp_topgo_5:'Координировал техническое взаимодействие с внешними подрядчиками по разработке и тестированию.',
    exp_thrive_role:'Ведущий PHP-разработчик, удаленный контракт', exp_thrive_1:'Работал над крупной e-commerce платформой по продаже органических продуктов по подписочной модели.', exp_thrive_2:'Интегрировал систему очередей Kafka в экосистему Magento для повышения отказоустойчивости и масштабируемости.', exp_thrive_3:'Спроектировал и реализовал систему автоматической повторяемой доставки товаров.', exp_thrive_4:'Поддерживал интеграции с Braintree, DHL, Sailthru и другими внешними сервисами.', exp_thrive_5:'Разрабатывал REST API и покрывал бизнес-логику автоматизированными тестами.',
    exp_bloom_role:'Ведущий PHP-разработчик, удаленный контракт', exp_bloom_1:'Развивал Magento-маркетплейс для продавцов цветочной продукции.', exp_bloom_2:'Разрабатывал личный кабинет продавца, управление каталогом товаров и обработку заказов.', exp_bloom_3:'Оптимизировал процессы продавцов с помощью асинхронной обработки данных и очередей.', exp_bloom_4:'Интегрировал Stripe и сопутствующие сервисы.', exp_bloom_5:'Участвовал в развитии мультидоменной платформы для маркетплейса и отдельных сайтов продавцов.',
    more_project:'Подробнее', exp_headmage_more_1:'Работал с заказчиками напрямую: помогал превращать бизнес-задачи в понятные технические требования и план разработки.', exp_headmage_more_2:'Подбирал решения под бюджет, сроки и состояние существующего проекта: от доработки legacy-кода до проектирования новых модулей.', exp_headmage_more_3:'Совмещал техническую работу с управлением командой: постановка задач, проверка решений, контроль релизов и поддержка после запуска.', exp_saby_more_1:'Работал с проблемной платформой, где было важно повысить стабильность изменений и снизить количество ошибок.', exp_saby_more_2:'Внедрение автотестов и TDD помогало безопаснее менять бизнес-логику и быстрее проверять корректность доработок.', exp_saby_more_3:'Code Review использовался не только для контроля качества, но и для выравнивания подходов внутри подразделения.', exp_topgo_more_1:'Kafka использовалась для доставки событий уведомлений без блокировки основного сценария работы сервиса.', exp_topgo_more_2:'ClickHouse был интегрирован как хранилище аналитических данных, логов и истории действий с возможностью автоматической очистки устаревших записей.', exp_topgo_more_3:'Отдельное внимание уделялось отказоустойчивости и предсказуемому деплою в облачной инфраструктуре.', exp_thrive_more_1:'Работал с критичными частями e-commerce платформы: подписки, повторные заказы, платежи, логистика и внешние интеграции.', exp_thrive_more_2:'Kafka помогала выносить тяжелые и асинхронные операции из основного пользовательского сценария.', exp_thrive_more_3:'Поддерживал REST-слой для frontend-приложений и писал автоматизированные тесты для бизнес-логики.', exp_bloom_more_1:'Проект был не обычным интернет-магазином, а маркетплейсом с большим количеством продавцов и отдельными сайтами.', exp_bloom_more_2:'Работал с кабинетом продавца, каталогом, заказами, промо-механиками и мультидоменной архитектурой Magento.', exp_bloom_more_3:'Асинхронная обработка помогала ускорять операции продавцов и снижать нагрузку на основную систему.', current_eyebrow:'Сейчас', current_title:'Текущая деятельность', current_text:'Проектная разработка и поддержка веб-систем. Последний проект — CRM для агентства недвижимости на Laravel.', current_more_title:'Подробнее о текущем проекте', current_more_1:'Проектирование архитектуры CRM-системы с нуля на Laravel.', current_more_2:'Автоматический сбор, парсинг и обработка данных по рынку недвижимости из разных источников.', current_more_3:'Интеграция SMS, Email и внешних сервисов уведомлений.', current_more_4:'Использование AI-инструментов для обработки входящей информации и анализа данных.', current_more_5:'Цель проекта — автоматизация внутренних процессов и снижение ручной работы сотрудников агентства.', contacts_eyebrow:'Контакты', contacts_title:'Обсудим ваш проект', contacts_text:'Подходит формат проектной работы, контракта, поддержки или разработки системы под ключ.'
  },
  en: {
    nav_services:'Services', nav_experience:'Experience', nav_contacts:'Contacts', eyebrow:'Project work • Contract • Self-employed', hero_title:'Vladimir S.', hero_subtitle:'Web systems, e-commerce and CRM development', hero_copy:'15+ years of commercial experience. I deliver full-cycle projects: architecture, backend development, integrations, infrastructure setup and launch.', btn_telegram:'Message on Telegram', btn_email:'Send Email', btn_pdf_ru:'Открыть PDF', btn_pdf_en:'Open PDF', status:'Open to project collaboration', services_eyebrow:'What I do', services_title:'Development and support of complex web systems', srv_crm_title:'CRM and internal systems', srv_crm_text:'Architecture and development of business systems with Laravel, integrations, roles and process automation.', srv_shop_title:'E-commerce platforms', srv_shop_text:'Magento, Laravel, payment systems, subscriptions, catalogs, seller dashboards and optimization.', srv_audit_title:'Audit and optimization', srv_audit_text:'Finding bottlenecks, optimizing SQL, performance, architecture and security risks.', srv_integr_title:'Integrations and data', srv_integr_text:'REST API, Kafka, Redis, ClickHouse, parsing, queues, notifications and third-party services.', profile_eyebrow:'Profile', profile_title:'Developer, technical lead and solution architect experience', profile_1:'6 years managing my own web studio: estimation, planning, team, releases and direct communication with clients.', profile_2:'Specialized in architecture, high-load systems, integrations, performance audits and legacy project support.', profile_3:'I can take a full-cycle project: from idea and requirements to launch and further development.', tech_eyebrow:'Stack', tech_title:'Technologies', exp_eyebrow:'Experience', exp_title:'Key projects',
    exp_headmage_role:'Founder / Technical Director of a web studio', exp_headmage_1:'Managed my own web studio focused on Laravel, Magento, CRM and e-commerce projects.', exp_headmage_2:'Designed architecture for online stores, CRM systems and integration solutions for Russian and international clients.', exp_headmage_3:'Owned the full delivery cycle: estimation, planning, development, releases, launch and ongoing support.', exp_headmage_4:'Set up development processes, Code Review, CI/CD and release workflows using Jenkins.',
    exp_saby_role:'Department Lead / Senior Python Developer', exp_saby_1:'Developed a platform for search, processing and analysis of company and owner data.', exp_saby_2:'Built search, filtering and large-volume data processing functionality with Python and PostgreSQL.', exp_saby_3:'Introduced automated tests and TDD practices to improve development quality.', exp_saby_4:'Optimized business logic and SQL queries to improve platform performance.', exp_saby_5:'Prepared and decomposed tasks, performed Code Review and contributed to development process improvements.',
    exp_topgo_role:'Senior PHP Developer / Microservices Architect', exp_topgo_1:'Designed and implemented a fault-tolerant notification microservice for a courier delivery aggregator.', exp_topgo_2:'Implemented Kafka for fast and reliable delivery of notifications to couriers.', exp_topgo_3:'Integrated ClickHouse for storing analytical data, logs and action history.', exp_topgo_4:'Configured CI/CD pipelines for automated build and deployment in Yandex Cloud.', exp_topgo_5:'Coordinated technical communication with external development and QA contractors.',
    exp_thrive_role:'Senior PHP Developer, remote contract', exp_thrive_1:'Worked on a large e-commerce platform for organic products with a subscription business model.', exp_thrive_2:'Integrated Kafka queues into the Magento ecosystem to improve fault tolerance and scalability.', exp_thrive_3:'Designed and implemented an automatic recurring delivery system for products.', exp_thrive_4:'Maintained integrations with Braintree, DHL, Sailthru and other third-party services.', exp_thrive_5:'Developed REST API and covered business logic with automated tests.',
    exp_bloom_role:'Senior PHP Developer, remote contract', exp_bloom_1:'Developed a Magento marketplace for flower sellers.', exp_bloom_2:'Built seller dashboard functionality, catalog management and order processing.', exp_bloom_3:'Optimized seller workflows using asynchronous data processing and queues.', exp_bloom_4:'Integrated Stripe and related services.', exp_bloom_5:'Contributed to a multi-domain platform for marketplace listings and standalone seller websites.',
    more_project:'More details', exp_headmage_more_1:'Worked directly with clients: helped translate business needs into clear technical requirements and delivery plans.', exp_headmage_more_2:'Selected solutions based on budget, deadlines and the current state of the project: from legacy improvements to new module design.', exp_headmage_more_3:'Combined technical work with team management: task setting, solution review, release control and post-launch support.', exp_saby_more_1:'Worked with a problematic platform where stability of changes and reducing errors were critical.', exp_saby_more_2:'Automated tests and TDD practices helped change business logic more safely and verify improvements faster.', exp_saby_more_3:'Code Review was used not only for quality control but also for aligning engineering approaches inside the department.', exp_topgo_more_1:'Kafka was used to deliver notification events without blocking the main service workflow.', exp_topgo_more_2:'ClickHouse was integrated as storage for analytical data, logs and action history, including automatic cleanup of outdated records.', exp_topgo_more_3:'Special attention was paid to fault tolerance and predictable deployment in cloud infrastructure.', exp_thrive_more_1:'Worked with business-critical areas of the e-commerce platform: subscriptions, recurring orders, payments, logistics and integrations.', exp_thrive_more_2:'Kafka helped move heavy and asynchronous operations out of the main user flow.', exp_thrive_more_3:'Maintained the REST layer for frontend applications and wrote automated tests for business logic.', exp_bloom_more_1:'The project was not a simple online store but a marketplace with many sellers and standalone seller websites.', exp_bloom_more_2:'Worked on seller dashboards, catalog, orders, promotion mechanics and Magento multi-domain architecture.', exp_bloom_more_3:'Asynchronous processing helped speed up seller operations and reduce load on the main system.', current_eyebrow:'Now', current_title:'Current activity', current_text:'Project-based development and support of web systems. Latest project: CRM for a real estate agency using Laravel.', current_more_title:'More about the current project', current_more_1:'Designing CRM architecture from scratch using Laravel.', current_more_2:'Automated collection, parsing and processing of real estate market data from different sources.', current_more_3:'Integration of SMS, Email and third-party notification services.', current_more_4:'Using AI tools to process incoming information and analyze data.', current_more_5:'Project goal: automate internal processes and reduce manual work for agency employees.', contacts_eyebrow:'Contacts', contacts_title:'Let’s discuss your project', contacts_text:'Project work, contract development, support or turnkey system development.'
  }
};
let lang = 'ru';
const switcher = document.getElementById('langSwitch');
function setLang(next){
  lang = next;
  document.documentElement.lang = next;
  document.querySelectorAll('[data-i18n]').forEach(el => { const key = el.dataset.i18n; if(translations[next][key]) el.textContent = translations[next][key]; });
  switcher.textContent = next === 'ru' ? 'EN' : 'RU';
  document.querySelector('[data-download-ru]').classList.toggle('hidden', next !== 'ru');
  document.querySelector('[data-download-en]').classList.toggle('hidden', next !== 'en');
  document.title = next === 'ru' ? 'Владимир С. — WebSystems Backend' : 'Vladimir S. — WebSystems Backend';
}
switcher.addEventListener('click', () => setLang(lang === 'ru' ? 'en' : 'ru'));
document.getElementById('year').textContent = new Date().getFullYear();
setLang('ru');
